server:
  address: 0.0.0.0
spring:
  application:
    name: PosthorseCloudDelivery
  sql:
    init:
      schema-locations: classpath:init.sql
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

app:
  resource:
    location:
      upload:
        origin: file:./upload/
        mapping: /upload/**